{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(mysql_global_status_threads_connected[1m]))",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(mysql_global_status_max_used_connections)",
     "legendFormat": "Max Used Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(max_over_time(mysql_global_status_threads_connected[1m]))",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "expr": "sum(max_over_time(mysql_global_status_threads_running[1m]))",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "sum(avg_over_time(mysql_global_status_threads_running[1m]))",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_page_size{job=~\"mysqld-exporter\", instance=~\"ddg-mysql-dbms:3306\"} * on (instance) mysql_global_status_buffer_pool_pages{job=~\"mysqld-exporter\", instance=~\"ddg-mysql-dbms:3306\", state=\"data\"})",
     "legendFormat": "InnoDB Buffer Pool Data"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_bytes_received{job=~\"mysqld-exporter\", instance=~\"ddg-mysql-dbms:3306\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(mysql_global_status_bytes_sent{job=~\"mysqld-exporter\", instance=~\"ddg-mysql-dbms:3306\"}[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}