{
 "title": "OS General",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{device=\"enp1s0\"}[10m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{device=\"enp1s0\"}[10m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Number of kernel file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "File descriptors count" }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  }
 ]
}