global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: node-exporter
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - <YOUR VM IP ADDRESS>:9100

  - job_name: mysqld-exporter
    static_configs:
      - targets:
        - ddg-mysql-dbms:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ddg-mysqld-exporter:9104

remote_write:
  - url: "<Your Prometheus remote_write endpoint>"
    basic_auth:
      username: "<Your Grafana Username>"
      password: "<Your Grafana API key>"

